const careers = [
    {
        name: "Quantum Algorithm Designer 🌌",
        category: "Quantum Computing Research",
        skills: ["Quantum Mechanics", "Algorithm Design", "Linear Algebra"],
        tools: ["Qiskit", "Q#", "Cirq"],
        salaryINR: "₹20-40 LPA",
        salaryUSD: "$150k-$250k",
        funFact: "Quantum computers can solve certain problems exponentially faster than classical computers!",
        resourceLink: "https://www.coursera.org/specializations/robotics",
        companies: ["IBM Quantum", "Google Quantum AI", "Microsoft Quantum", "IonQ", "Rigetti Computing"]
    },
    {
        name: "Bio-Inspired Computing Researcher 🧬",
        category: "Theoretical Computer Science",
        skills: ["Neural Networks", "Evolutionary Algorithms", "Biology"],
        tools: ["Python", "TensorFlow", "Custom Simulators"],
        salaryINR: "₹15-30 LPA",
        salaryUSD: "$120k-$180k",
        funFact: "Ant colony algorithms are used to solve complex routing problems!",
        resourceLink: "https://www.sciencedirect.com/topics/computer-science/bio-inspired-computing",
        companies: ["DeepMind", "Numenta", "Caltech Bio-Inspired Lab", "Turing Intelligence Technology", "GoodAI"]
    },
    {
        name: "Quantum Cryptography Expert 🔐",
        category: "Security Research",
        skills: ["Quantum Physics", "Cryptography", "Mathematics"],
        tools: ["QKD Systems", "Custom Security Tools", "Python"],
        salaryINR: "₹18-35 LPA",
        salaryUSD: "$140k-$220k",
        funFact: "Quantum cryptography is theoretically unbreakable!",
        resourceLink: "https://www.coursera.org/specializations/software-design-architecture",
        companies: ["ID Quantique", "QuintessenceLabs", "Toshiba QKD", "MagiQ Technologies", "Post-Quantum"]
    },
    {
        name: "Quantum Computing Engineer 🌌",
        category: "Quantum Computing",
        skills: ["Quantum Mechanics", "Linear Algebra", "Quantum Algorithms"],
        tools: ["Qiskit", "Q#", "IBM Quantum"],
        salaryINR: "₹15-30 LPA",
        salaryUSD: "$120k-$200k",
        funFact: "A quantum computer with 300 qubits can perform more calculations simultaneously than there are atoms in the universe!",
        resourceLink: "https://www.coursera.org/professional-certificates/gcp-cloud-architect"
    },
    {
        name: "Edge Computing Architect 🌐",
        category: "Distributed Systems",
        skills: ["5G Networks", "IoT", "Distributed Computing"],
        tools: ["AWS Greengrass", "Azure IoT Edge", "Docker"],
        salaryINR: "₹18-35 LPA",
        salaryUSD: "$130k-$180k",
        funFact: "Edge computing can reduce internet bandwidth usage by up to 95% for IoT devices.",
        resourceLink: "https://aws.amazon.com/greengrass/",
        companies: ["AWS", "Microsoft Azure", "Google Cloud", "Cisco", "VMware"]
    },
    {
        name: "AR/VR Experience Architect 🥽",
        category: "Extended Reality",
        skills: ["3D Modeling", "UX Design", "Spatial Computing"],
        tools: ["Unity", "Unreal Engine", "ARKit/ARCore"],
        salaryINR: "₹15-35 LPA",
        salaryUSD: "$120k-$180k",
        funFact: "The VR training market is expected to grow to $294.15 billion by 2030!",
        resourceLink: "https://learn.unity.com/",
        companies: ["Meta Reality Labs", "Microsoft HoloLens", "Magic Leap", "Unity Technologies", "Niantic"]
    },
    {
        name: "Blockchain Solutions Architect 🔗",
        category: "Distributed Systems",
        skills: ["Smart Contracts", "Cryptography", "DApp Development"],
        tools: ["Solidity", "Web3.js", "Truffle"],
        salaryINR: "₹20-45 LPA",
        salaryUSD: "$150k-$220k",
        funFact: "The first smart contract was created in 1994, way before Bitcoin!",
        resourceLink: "https://ethereum.org/developers",
        companies: ["Ethereum Foundation", "Consensys", "Ripple", "Binance", "Polygon"]
    },
    {
        name: "Robotics Software Engineer 🤖",
        category: "Robotics",
        skills: ["ROS", "Computer Vision", "Control Systems"],
        tools: ["Python", "C++", "MATLAB"],
        salaryINR: "₹18-40 LPA",
        salaryUSD: "$130k-$200k",
        funFact: "Robot density in manufacturing is highest in South Korea with 932 robots per 10,000 employees!",
        resourceLink: "https://www.ros.org/",
        companies: ["Boston Dynamics", "iRobot", "FANUC", "ABB Robotics", "Cruise"]
    },
    {
        name: "Digital Ethics Officer 🎯",
        category: "AI Ethics",
        skills: ["AI Ethics", "Policy Development", "Risk Assessment"],
        tools: ["Ethics Frameworks", "Audit Tools", "Compliance Software"],
        salaryINR: "₹25-50 LPA",
        salaryUSD: "$160k-$250k",
        funFact: "71% of companies now consider AI ethics a board-level issue!",
        resourceLink: "https://www.coursera.org/learn/ai-ethics",
        companies: ["OpenAI", "Google AI Ethics", "Microsoft Ethics & Society", "IBM Research", "DeepMind Ethics"]
    },
    {
        name: "Metaverse Systems Engineer 🌐",
        category: "Virtual Worlds",
        skills: ["3D Development", "Networking", "Virtual Economics"],
        tools: ["Unity", "WebXR", "Blockchain"],
        salaryINR: "₹20-40 LPA",
        salaryUSD: "$140k-$210k",
        companies: ["Meta", "Roblox", "Epic Games", "Decentraland", "The Sandbox"],
        funFact: "The term 'metaverse' was first coined in 1992 in the science fiction novel 'Snow Crash'!",
        resourceLink: "https://metaverse.dev"
    },
    {
        name: "Quantum Machine Learning Engineer 🧮",
        category: "Quantum Computing",
        skills: ["Quantum Algorithms", "ML/DL", "Linear Algebra"],
        tools: ["TensorFlow Quantum", "Qiskit", "PennyLane"],
        salaryINR: "₹25-45 LPA",
        salaryUSD: "$170k-$240k",
        funFact: "Quantum computers can potentially break current encryption methods in seconds!",
        resourceLink: "https://tensorflow.org/quantum",
        companies: ["Google Quantum AI", "Xanadu", "Zapata Computing", "Cambridge Quantum", "QC Ware"]
    },
    {
        name: "Neurotech Interface Developer 🧠",
        category: "Brain-Computer Interfaces",
        skills: ["Neuroscience", "Signal Processing", "ML"],
        tools: ["Python", "TensorFlow", "NeuroTech SDKs"],
        salaryINR: "₹30-55 LPA",
        salaryUSD: "$180k-$260k",
        funFact: "The human brain processes images seen for as little as 13 milliseconds!",
        resourceLink: "https://neuralink.com/developer",
        companies: ["Neuralink", "Kernel", "CTRL-labs", "Synchron", "NextMind"]
    },
    {
        name: "Space Systems Software Engineer 🚀",
        category: "Space Technology",
        skills: ["Embedded Systems", "Telemetry", "Control Systems"],
        tools: ["C++", "RTOS", "COSMOS"],
        salaryINR: "₹20-45 LPA",
        salaryUSD: "$150k-$230k",
        funFact: "Space vehicles use radiation-hardened computers that are decades old but super reliable!",
        resourceLink: "https://www.nasa.gov/software/",
        companies: ["SpaceX", "NASA", "Blue Origin", "Rocket Lab", "Virgin Galactic"]
    },
    {
        name: "Autonomous Vehicle AI Specialist 🚗",
        category: "Automotive AI",
        skills: ["Computer Vision", "Sensor Fusion", "Path Planning"],
        tools: ["ROS", "TensorFlow", "CARLA"],
        salaryINR: "₹25-50 LPA",
        salaryUSD: "$160k-$240k",
        funFact: "Self-driving cars generate about 4 terabytes of data per day of testing!",
        resourceLink: "https://www.autoware.org/",
        companies: ["Tesla", "Waymo", "Cruise", "Aurora", "Argo AI"]
    },
    {
        name: "Synthetic Biology Programmer 🧬",
        category: "BioInformatics",
        skills: ["Gene Sequencing", "Molecular Biology", "Python"],
        tools: ["BioPython", "BLAST", "Genome Compiler"],
        salaryINR: "₹18-40 LPA",
        salaryUSD: "$140k-$200k",
        funFact: "DNA can store 215 petabytes of data in a single gram!",
        resourceLink: "https://biopython.org/",
        companies: ["Ginkgo Bioworks", "Illumina", "23andMe", "Twist Bioscience", "Benchling"]
    },
    {
        name: "IoT Security Architect 🔒",
        category: "Security",
        skills: ["Network Security", "Embedded Systems", "Cryptography"],
        tools: ["Wireshark", "Metasploit", "ARM TrustZone"],
        salaryINR: "₹20-45 LPA",
        salaryUSD: "$150k-$220k",
        funFact: "There will be over 75 billion IoT devices by 2025!",
        resourceLink: "https://www.iotsecurity.io/",
        companies: ["Cisco IoT", "ARM Security", "Palo Alto Networks", "Fortinet", "Zscaler"]
    },
    {
        name: "Digital Twin Engineer 👥",
        category: "Industrial IoT",
        skills: ["3D Modeling", "Data Analytics", "IoT"],
        tools: ["Unity", "Azure Digital Twins", "ThingWorx"],
        salaryINR: "₹18-40 LPA",
        salaryUSD: "$130k-$190k",
        funFact: "NASA was first to use digital twins for space exploration!",
        resourceLink: "https://azure.microsoft.com/digital-twins",
        companies: ["Siemens Digital", "GE Digital", "Microsoft Azure", "PTC", "Bosch IoT"]
    },
    {
        name: "Cloud Robotics Engineer ☁️",
        category: "Robotics",
        skills: ["Cloud Computing", "ROS", "Distributed Systems"],
        tools: ["AWS RoboMaker", "Google Cloud Robotics", "Docker"],
        salaryINR: "₹20-45 LPA",
        salaryUSD: "$140k-$210k",
        funFact: "Cloud-connected robots can share learned behaviors with each other!",
        resourceLink: "https://aws.amazon.com/robomaker/",
        companies: ["AWS Robotics", "Google Cloud Robotics", "NVIDIA Isaac", "Fetch Robotics", "Rapyuta Robotics"]
    },
    {
        name: "Quantum Cryptography Developer 🔐",
        category: "Security",
        skills: ["Quantum Physics", "Cryptography", "Network Security"],
        tools: ["QKD Systems", "OpenQKD", "Python"],
        salaryINR: "₹25-50 LPA",
        salaryUSD: "$170k-$240k",
        funFact: "Quantum cryptography is theoretically unhackable due to quantum mechanics laws!",
        resourceLink: "https://openqkd.org/"
    },
    {
        name: "Edge AI Architect 🌐",
        category: "AI/ML",
        skills: ["Machine Learning", "Embedded Systems", "Optimization"],
        tools: ["TensorFlow Lite", "Edge TPU", "Arduino"],
        salaryINR: "₹20-45 LPA",
        salaryUSD: "$150k-$220k",
        funFact: "Edge AI can reduce cloud computing costs by up to 70%!",
        resourceLink: "https://coral.ai/",
        companies: ["Google Coral", "NVIDIA Jetson", "Intel Edge AI", "Qualcomm AI", "Edge Impulse"]
    },
    {
        name: "Holographic Display Developer 📺",
        category: "Display Technology",
        skills: ["Computer Graphics", "Optics", "3D Modeling"],
        tools: ["Unity", "HoloLens SDK", "OpenGL"],
        salaryINR: "₹15-35 LPA",
        salaryUSD: "$120k-$180k",
        funFact: "The largest hologram ever made was the size of a house!",
        resourceLink: "https://microsoft.com/hololens",
        companies: ["Microsoft HoloLens", "Magic Leap", "Looking Glass Factory", "Light Field Lab", "VOXON"]
    },
    {
        name: "Smart City Solutions Architect 🏙️",
        category: "Urban Tech",
        skills: ["IoT", "Data Analytics", "Urban Planning"],
        tools: ["AWS IoT", "Cisco Kinetic", "FIWARE"],
        salaryINR: "₹20-45 LPA",
        salaryUSD: "$140k-$210k",
        funFact: "Smart cities can reduce energy consumption by up to 30%!",
        resourceLink: "https://www.fiware.org/",
        companies: ["Cisco Smart Cities", "Siemens Smart Infrastructure", "IBM Smart Cities", "Hitachi Smart Spaces", "Sidewalk Labs"]
    },
    {
        name: "Quantum Network Engineer 🌐",
        category: "Quantum Computing",
        skills: ["Quantum Mechanics", "Networking", "Cryptography"],
        tools: ["QuTiP", "Q#", "OpenQASM"],
        salaryINR: "₹25-50 LPA",
        salaryUSD: "$160k-$230k",
        funFact: "China has a quantum communication satellite that's unhackable!",
        resourceLink: "https://www.coursera.org/learn/quantum-computing-algorithms"
    },
    {
        name: "Bio-Inspired AI Researcher 🦋",
        category: "AI Research",
        skills: ["Deep Learning", "Biology", "Algorithm Design"],
        tools: ["PyTorch", "NumPy", "BioPython"],
        salaryINR: "₹20-45 LPA",
        salaryUSD: "$150k-$220k",
        funFact: "Ant colony algorithms help optimize network routing!",
        resourceLink: "https://bio-ai.org",
        companies: ["DeepMind", "OpenAI", "Max Planck Institute", "Caltech Bio-AI Lab", "Harvard Wyss Institute"]
    },
    {
        name: "Mixed Reality Game Developer 🎮",
        category: "Game Development",
        skills: ["Unity/Unreal", "AR/VR", "Game Design"],
        tools: ["Unity", "ARKit", "Vuforia"],
        salaryINR: "₹15-35 LPA",
        salaryUSD: "$120k-$180k",
        funFact: "The mixed reality market will reach $100B by 2026!",
        resourceLink: "https://unity.com/ar",
        companies: ["Niantic", "Unity Technologies", "Epic Games", "Resolution Games", "Owlchemy Labs"]
    },
    {
        name: "Sustainable Computing Architect 🌱",
        category: "Green Technology",
        skills: ["Energy Optimization", "Cloud Computing", "Carbon Footprint Analysis"],
        tools: ["Green Algorithms", "Cloud Carbon Footprint", "PowerAPI"],
        salaryINR: "₹20-40 LPA",
        salaryUSD: "$140k-$200k",
        funFact: "Data centers use about 1% of global electricity consumption!",
        resourceLink: "https://green-algorithms.org",
        companies: ["Google Sustainability", "Microsoft Sustainability", "Intel Energy", "Tesla Green Tech", "Schneider Electric"]
    },
    {
        name: "Human-Robot Interaction Designer 🤝",
        category: "Robotics",
        skills: ["UX Design", "Psychology", "Robotics"],
        tools: ["ROS", "Unity", "PyRobot"],
        salaryINR: "₹18-40 LPA",
        salaryUSD: "$130k-$190k",
        funFact: "Robots can now recognize and respond to human emotions!",
        resourceLink: "https://ros.org/hri",
        companies: ["Softbank Robotics", "Boston Dynamics", "Hanson Robotics", "Diligent Robotics", "Honda Robotics"]
    },
    {
        name: "Quantum Game Developer 🎲",
        category: "Game Development",
        skills: ["Game Design", "Quantum Computing", "UI/UX"],
        tools: ["Unity", "Qiskit", "Python"],
        salaryINR: "₹15-35 LPA",
        salaryUSD: "$120k-$170k",
        funFact: "Quantum games help people understand quantum mechanics intuitively!",
        resourceLink: "https://quantum-games.org",
        companies: ["IBM Quantum Games", "Microsoft Quantum", "Google Quantum AI", "D-Wave Games", "QuCrypt Games"]
    },
    {
        name: "Neural Interface Programmer 🧠",
        category: "BioTechnology",
        skills: ["Neuroscience", "Signal Processing", "Machine Learning"],
        tools: ["BrainFlow", "TensorFlow", "OpenBCI"],
        salaryINR: "₹25-50 LPA",
        salaryUSD: "$160k-$230k",
        funFact: "Brain-computer interfaces can help paralyzed patients type with their thoughts!",
        resourceLink: "https://openbci.com",
        companies: ["Neuralink", "Kernel", "Paradromics", "BrainCo", "Emotiv"]
    },
    {
        name: "Space Data Engineer 🛸",
        category: "Space Technology",
        skills: ["Big Data", "Astronomy", "Machine Learning"],
        tools: ["Apache Spark", "AstroPy", "NASA APIs"],
        salaryINR: "₹20-45 LPA",
        salaryUSD: "$140k-$210k",
        funFact: "Space telescopes generate over 150GB of data per day!",
        resourceLink: "https://nasa.github.io/",
        companies: ["NASA", "SpaceX", "ESA", "Planet Labs", "Maxar Technologies"]
    },
    {
        name: "Swarm Robotics Engineer 🤖",
        category: "Robotics",
        skills: ["Multi-Agent Systems", "Control Theory", "AI"],
        tools: ["ROS", "Gazebo", "Python"],
        salaryINR: "₹20-40 LPA",
        salaryUSD: "$140k-$200k",
        funFact: "Robot swarms can self-organize like bee colonies!",
        resourceLink: "https://swarm-robotics.org",
        companies: ["Raytheon", "Lockheed Martin", "iRobot", "Shield AI", "SwarmFarm Robotics"]
    },
    {
        name: "Quantum Financial Engineer 💹",
        category: "FinTech",
        skills: ["Quantum Computing", "Finance", "Algorithm Design"],
        tools: ["Qiskit", "Python", "D-Wave"],
        salaryINR: "₹30-60 LPA",
        salaryUSD: "$180k-$250k",
        funFact: "Quantum computers can optimize investment portfolios exponentially faster!",
        resourceLink: "https://qiskit.org/finance",
        companies: ["JPMorgan Chase Quantum", "Goldman Sachs", "Barclays Quantum", "QC Ware Finance", "1QBit"]
    },
    {
        name: "Digital Agriculture Engineer 🌾",
        category: "AgriTech",
        skills: ["IoT", "Data Analytics", "Machine Learning"],
        tools: ["TensorFlow", "Arduino", "Satellite APIs"],
        salaryINR: "₹15-35 LPA",
        salaryUSD: "$120k-$180k",
        funFact: "AI-powered farming can reduce water usage by 30%!",
        resourceLink: "https://agritech.org",
        companies: ["John Deere Digital", "Climate Corporation", "Farmers Edge", "Indigo Ag", "Plenty"]
    },
    {
        name: "Humanoid Robotics Specialist 🤖",
        category: "Robotics",
        skills: ["Kinematics", "Computer Vision", "Control Systems"],
        tools: ["ROS", "PyBullet", "OpenCV"],
        salaryINR: "₹25-50 LPA",
        salaryUSD: "$160k-$230k",
        funFact: "The most advanced humanoid robots can now do backflips!",
        resourceLink: "https://humanoid-robotics.org"
    },
    {
        name: "Quantum Education Developer 📚",
        category: "EdTech",
        skills: ["Quantum Computing", "Education", "Game Design"],
        tools: ["Qiskit", "Unity", "Python"],
        salaryINR: "₹15-35 LPA",
        salaryUSD: "$120k-$180k",
        funFact: "Interactive quantum simulations help students learn complex concepts 50% faster!",
        resourceLink: "https://qiskit.org/education"
    }
    ,
    {
        name: "Neurotech Developer 🧬",
        category: "Brain-Computer Interfaces",
        skills: ["Signal Processing", "Machine Learning", "Neuroscience"],
        tools: ["BrainFlow", "MNE-Python", "OpenBCI"],
        salaryINR: "₹20-40 LPA",
        salaryUSD: "$150k-$250k",
        funFact: "Brain-computer interfaces can help paralyzed individuals control computers with their thoughts!",
        resourceLink: "https://openbci.com/"
    },
    {
        name: "Smart Contract Auditor 🔍",
        category: "Blockchain Security",
        skills: ["Solidity", "Security Analysis", "DeFi Protocols"],
        tools: ["Slither", "Mythril", "Echidna"],
        salaryINR: "₹15-35 LPA",
        salaryUSD: "$130k-$200k",
        funFact: "A single smart contract bug once froze over $300 million worth of cryptocurrency!",
        resourceLink: "https://consensys.net/diligence/"
    },
    {
        name: "Holographic App Developer 👓",
        category: "Mixed Reality",
        skills: ["Spatial Computing", "3D Graphics", "UX Design"],
        tools: ["Unity MRTK", "HoloLens SDK", "ARCore"],
        salaryINR: "₹12-25 LPA",
        salaryUSD: "$100k-$160k",
        funFact: "Holographic displays can create 3D images visible without special glasses!",
        resourceLink: "https://mixedrealitytoolkit.io/"
    },
    {
        name: "Software Engineer 💻",
        category: "Software Development",
        skills: ["Programming", "Problem Solving", "Version Control"],
        tools: ["Git", "VS Code", "Jira"],
        salaryINR: "₹6-12 LPA",
        salaryUSD: "$70k-$120k",
        funFact: "The term 'software engineering' was popularized in the late 1960s.",
        resourceLink: "https://roadmap.sh/software-engineer",
        companies: ["Google", "Microsoft", "Apple", "Meta", "Amazon"]
    },
    {
        name: "AI Research Scientist 🧠",
        category: "Artificial Intelligence",
        skills: ["Machine Learning", "Deep Learning", "Python"],
        tools: ["TensorFlow", "PyTorch", "NumPy"],
        salaryINR: "₹10-25 LPA",
        salaryUSD: "$100k-$150k",
        funFact: "AI research dates back to the 1950s with the Dartmouth Conference.",
        resourceLink: "https://www.deeplearning.ai/",
        companies: ["DeepMind", "OpenAI", "Google Brain", "Microsoft Research", "IBM Research"]
    },
    {
        name: "Data Scientist 📊",
        category: "Data & Analytics",
        skills: ["Statistics", "Data Visualization", "SQL"],
        tools: ["Pandas", "Tableau", "R"],
        salaryINR: "₹8-18 LPA",
        salaryUSD: "$95k-$140k",
        funFact: "Data scientists spend about 80% of their time cleaning data.",
        resourceLink: "https://roadmap.sh/data-scientist",
        companies: ["Databricks", "Palantir", "Netflix", "Uber", "Airbnb"]
    },
    {
        name: "Cloud Solutions Architect ☁️",
        category: "Cloud Computing",
        skills: ["Cloud Platforms", "Networking", "Security"],
        tools: ["AWS", "Azure", "GCP"],
        salaryINR: "₹12-25 LPA",
        salaryUSD: "$110k-$160k",
        funFact: "Cloud computing reduces infrastructure costs by up to 50%.",
        resourceLink: "https://aws.amazon.com/architecture/",
        companies: ["Amazon AWS", "Microsoft Azure", "Google Cloud", "Oracle Cloud", "IBM Cloud"]
    },
    {
        name: "Cybersecurity Analyst 🔐",
        category: "Security",
        skills: ["Network Security", "Incident Response", "Penetration Testing"],
        tools: ["Wireshark", "Metasploit", "Kali Linux"],
        salaryINR: "₹6-15 LPA",
        salaryUSD: "$80k-$130k",
        funFact: "Cybercrime damages are projected to cost $10.5 trillion annually by 2025.",
        resourceLink: "https://www.coursera.org/specializations/ibm-cybersecurity-analyst",
        companies: ["CrowdStrike", "Palo Alto Networks", "FireEye", "Cisco Security", "Kaspersky"]
    },
    {
        name: "Blockchain Developer ⛓️",
        category: "Blockchain & Web3",
        skills: ["Smart Contracts", "Solidity", "Cryptography"],
        tools: ["Ethereum", "Truffle", "Remix IDE"],
        salaryINR: "₹8-20 LPA",
        salaryUSD: "$90k-$140k",
        funFact: "Blockchain technology was first implemented in Bitcoin in 2009.",
        resourceLink: "https://ethereum.org/en/developers/"
    },
    {
        name: "Game Developer 🎮",
        category: "Gaming",
        skills: ["Game Design", "C++", "3D Modeling"],
        tools: ["Unity", "Unreal Engine", "Blender"],
        salaryINR: "₹4-12 LPA",
        salaryUSD: "$70k-$120k",
        funFact: "The first video game was created in 1958, called 'Tennis for Two'.",
        resourceLink: "https://learn.unity.com/",
        companies: ["Epic Games", "Ubisoft", "Electronic Arts", "Rockstar Games", "Nintendo"]
    },
    {
        name: "UX/UI Designer 🎨",
        category: "Design",
        skills: ["Wireframing", "Prototyping", "User Research"],
        tools: ["Figma", "Adobe XD", "Sketch"],
        salaryINR: "₹5-12 LPA",
        salaryUSD: "$75k-$110k",
        funFact: "Good UX can increase conversions by over 400%.",
        resourceLink: "https://www.interaction-design.org/",
        companies: ["Figma", "Adobe", "Google Design", "Apple Design", "Airbnb Design"]
    },
    {
        name: "DevOps Engineer ⚙️",
        category: "Operations",
        skills: ["CI/CD", "Automation", "Scripting"],
        tools: ["Docker", "Jenkins", "Kubernetes"],
        salaryINR: "₹8-16 LPA",
        salaryUSD: "$90k-$135k",
        funFact: "DevOps culture bridges the gap between development and operations teams.",
        resourceLink: "https://roadmap.sh/devops",
        companies: ["HashiCorp", "Red Hat", "Docker", "GitLab", "CircleCI"]
    },
    {
        name: "AR/VR Developer 🥽",
        category: "Extended Reality",
        skills: ["3D Modeling", "Unity", "C#"],
        tools: ["Oculus SDK", "ARKit", "Vuforia"],
        salaryINR: "₹6-15 LPA",
        salaryUSD: "$85k-$125k",
        funFact: "AR and VR are expected to be a $300B market by 2025.",
        resourceLink: "https://developer.oculus.com/"
    },
    {
        name: "Mobile App Developer 📱",
        category: "Mobile Development",
        skills: ["Mobile UI/UX", "Cross-platform Development", "API Integration"],
        tools: ["React Native", "Flutter", "Android Studio"],
        salaryINR: "₹5-15 LPA",
        salaryUSD: "$75k-$125k",
        funFact: "There are over 4 million mobile apps available for download.",
        resourceLink: "https://reactnative.dev/",
        companies: ["Google Android", "Apple iOS", "Meta", "Uber", "Instagram"]
    }
];
